title: "[General Discussion] "
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Share your thoughts, ideas, or questions about Chan-ZKP!
  - type: textarea
    id: discussion
    attributes:
      label: Discussion
      description: What would you like to discuss?
      placeholder: Share your thoughts, questions, or ideas...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context or background information
      placeholder: Optional context...

